/* Starter exercise library: names, cues and defaults, no videos. Loaded once for a trainer with an empty library. */
const E = (name, muscle, equipment, sets, reps, cues) => ({ name, muscle, equipment, sets, reps, cues, videoUrl: "" });

export const STARTER_EXERCISES = [
  E("Back Squat", "Legs", "Barbell", 4, "6-8", "Brace before you descend. Knees track over toes. Drive the floor away."),
  E("Goblet Squat", "Legs", "Dumbbell", 3, "10", "Elbows inside knees at the bottom. Chest tall. Sit between the hips."),
  E("Front Squat", "Legs", "Barbell", 4, "5", "Elbows high. Stay upright. Full foot pressure."),
  E("Bulgarian Split Squat", "Legs", "Dumbbell", 3, "8 each", "Front shin vertical-ish. Drop the back knee straight down. Push through the front heel."),
  E("Reverse Lunge", "Legs", "Dumbbell", 3, "8 each", "Step back long. Back knee kisses the floor. Return through the front foot."),
  E("Walking Lunge", "Legs", "Dumbbell", 3, "10 each", "Long stride, tall torso, control each step."),
  E("Step-Up", "Legs", "Dumbbell", 3, "8 each", "Whole foot on the box. Stand up through the top leg, don't push off the bottom."),
  E("Leg Press", "Legs", "Machine", 3, "10-12", "Low back stays on the pad. Control the bottom. Don't lock the knees."),
  E("Romanian Deadlift", "Hamstrings", "Barbell", 3, "8", "Soft knees, hips back, bar close to the legs. Stop when the hips stop."),
  E("Single-Leg RDL", "Hamstrings", "Dumbbell", 3, "8 each", "Square hips. Reach the back heel long. Slow on the way down."),
  E("Trap Bar Deadlift", "Full body", "Trap bar", 4, "5", "Wedge in, lats tight, push the floor away. Stand tall at the top."),
  E("Conventional Deadlift", "Full body", "Barbell", 4, "5", "Bar over midfoot. Take the slack out. Push, don't yank."),
  E("Hip Thrust", "Glutes", "Barbell", 3, "10", "Chin tucked, ribs down. Shins vertical at the top. Squeeze, pause."),
  E("Glute Bridge", "Glutes", "Bodyweight", 3, "12", "Heels close, ribs down, push through heels, pause at the top."),
  E("Hamstring Curl", "Hamstrings", "Machine", 3, "10-12", "Hips stay down. Slow lowering."),
  E("Leg Extension", "Quads", "Machine", 3, "12", "Pause at the top. Control down."),
  E("Calf Raise", "Calves", "Machine", 3, "12-15", "Full stretch at the bottom, pause at the top."),
  E("Bench Press", "Chest", "Barbell", 4, "6-8", "Shoulder blades pinned. Bar to lower chest. Feet driving."),
  E("Dumbbell Bench Press", "Chest", "Dumbbell", 3, "8-10", "Elbows about 45 degrees. Press up and slightly in."),
  E("Incline Dumbbell Press", "Chest", "Dumbbell", 3, "8-10", "Bench at 30 degrees. Elbows under wrists."),
  E("Push-Up", "Chest", "Bodyweight", 3, "10-15", "Straight line head to heels. Chest to the floor. Elbows back, not out."),
  E("Overhead Press", "Shoulders", "Barbell", 4, "6", "Squeeze glutes, ribs down. Head through at the top."),
  E("Half-Kneeling Dumbbell Press", "Shoulders", "Dumbbell", 3, "8 each", "Glute of the down knee squeezed. Press straight up, no lean."),
  E("Lateral Raise", "Shoulders", "Dumbbell", 3, "12-15", "Lead with the elbows. Stop at shoulder height. Slow down."),
  E("Face Pull", "Upper back", "Cable", 3, "15", "Pull to the eyes, thumbs back. Elbows high."),
  E("Pull-Up", "Back", "Bodyweight", 3, "AMRAP", "Full hang to chin over bar. Ribs down, no swinging."),
  E("Lat Pulldown", "Back", "Cable", 3, "10", "Chest up, pull elbows to the back pockets."),
  E("One-Arm Dumbbell Row", "Back", "Dumbbell", 3, "10 each", "Flat back. Pull the elbow toward the hip."),
  E("Seated Cable Row", "Back", "Cable", 3, "10-12", "Tall spine. Shoulder blades back, then elbows."),
  E("Chest-Supported Row", "Back", "Dumbbell", 3, "10", "Chest stays on the pad. Squeeze at the top."),
  E("Inverted Row", "Back", "Bodyweight", 3, "8-12", "Body straight. Pull chest to the bar."),
  E("Biceps Curl", "Arms", "Dumbbell", 3, "10-12", "Elbows pinned. No swinging."),
  E("Triceps Pushdown", "Arms", "Cable", 3, "12", "Elbows by the ribs. Lock out and squeeze."),
  E("Plank", "Core", "Bodyweight", 3, "30-45s", "Squeeze glutes, ribs down, push the floor away."),
  E("Side Plank", "Core", "Bodyweight", 3, "20-30s each", "Hips high, stacked. Long line through the body."),
  E("Dead Bug", "Core", "Bodyweight", 3, "8 each", "Low back pressed down. Exhale as the arm and leg reach."),
  E("Pallof Press", "Core", "Cable", 3, "10 each", "Press straight out and hold. Don't let the cable turn you."),
  E("Farmer Carry", "Full body", "Dumbbell", 3, "40 yd", "Tall posture, short quick steps, grip hard."),
  E("Suitcase Carry", "Core", "Dumbbell", 3, "30 yd each", "Weight in one hand. Stay perfectly upright."),
  E("Kettlebell Swing", "Full body", "Kettlebell", 3, "15", "Hinge, don't squat. Snap the hips. Bell floats to chest height."),
  E("Bird Dog", "Core", "Bodyweight", 2, "8 each", "Reach long, hips level, pause at the end."),
  E("Hip Flexor Stretch", "Mobility", "Bodyweight", 2, "30s each", "Tuck the pelvis, squeeze the back glute, shift forward gently.")
];
